spring:
  application:
    name: picngo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/picngo?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

weather:
  api:
    key: ${WEATHER_SERVICE_KEY}

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}
